const PIN='1060';
const subjects=['ENGLISH LANGUAGE','MATHEMATICS','INTEGRATED SCIENCE','SOCIAL STUDIES','GHANAIAN LANGUAGE','COMPUTING','R.M.E.','CAREER TECHNOLOGY','CREATIVE ARTS','FRENCH'];
const db=JSON.parse(localStorage.getItem('presecSBA')||'{"students":[],"scores":[]}');
const $=id=>document.getElementById(id); const save=()=>{localStorage.setItem('presecSBA',JSON.stringify(db));refresh()};
const clamp=(v,max)=>Math.max(0,Math.min(max,Number(v)||0));
function login(){if($('pin').value===PIN){sessionStorage.unlocked='1';$('login').classList.add('hidden');$('app').classList.remove('hidden');refresh()}else $('loginMsg').textContent='Incorrect PIN.'}
function lockApp(){sessionStorage.removeItem('unlocked');$('app').classList.add('hidden');$('login').classList.remove('hidden');$('pin').value=''}
$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
function go(page){document.querySelector(`button[data-page="${page}"]`)?.click()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');refresh()});
function grade(t){t=Number(t);if(t>=90)return[1,'HIGHEST'];if(t>=80)return[2,'HIGHER'];if(t>=70)return[3,'HIGH'];if(t>=60)return[4,'HIGH AVERAGE'];if(t>=55)return[5,'AVERAGE'];if(t>=50)return[6,'LOW AVERAGE'];if(t>=40)return[7,'LOW'];if(t>=35)return[8,'LOWER'];return[9,'FAIL']}
function ordinal(n){n=Number(n);if(!n)return '';let s=(n%100>=11&&n%100<=13)?'TH':({1:'ST',2:'ND',3:'RD'}[n%10]||'TH');return n+s}
function scoreFor(sid,sub){return db.scores.find(x=>x.studentId===sid&&x.subject===sub)||null}
function studentById(id){return db.students.find(s=>s.id===id)}
function saveStudent(){let id=$('sid').value.trim()||'STU-'+Date.now(),name=$('sname').value.trim();if(!name)return alert('Enter the student name.');let s={id,name,cls:$('sclass').value.trim(),section:$('ssection').value.trim(),dob:$('sdob').value,gender:$('sgender').value,term:$('sterm').value,year:$('syear').value,roll:$('sroll').value,attendance:$('sattendance').value,totalAttendance:$('stotalattendance').value};let old=studentById(id);if(old)Object.assign(old,s);else db.students.push(s);save();clearStudent()}
function clearStudent(){['sid','sname','sclass','ssection','sdob','sroll','sattendance','stotalattendance'].forEach(x=>$(x).value='');$('sgender').value='';$('sterm').value='ONE'}
function editStudent(id){let s=studentById(id);if(!s)return;[['sid',s.id],['sname',s.name],['sclass',s.cls],['ssection',s.section],['sdob',s.dob],['sroll',s.roll],['sattendance',s.attendance],['stotalattendance',s.totalAttendance]].forEach(([a,b])=>$(a).value=b||'');$('sgender').value=s.gender||'';$('sterm').value=s.term||'ONE';$('syear').value=s.year||'';go('students');scrollTo(0,0)}
function delStudent(id){if(confirm('Delete this student and all subject scores?')){db.students=db.students.filter(s=>s.id!==id);db.scores=db.scores.filter(x=>x.studentId!==id);save()}}
function saveScore(){let sid=$('scoreStudent').value,sub=$('scoreSubject').value;if(!sid||!sub)return alert('Select a student and subject.');let rec={studentId:sid,subject:sub,ct1:clamp($('ct1').value,30),ct2:clamp($('ct2').value,30),home:clamp($('home').value,20),group:clamp($('group').value,20),exam:clamp($('exam').value,100)};let old=db.scores.find(x=>x.studentId===sid&&x.subject===sub);if(old)Object.assign(old,rec);else db.scores.push(rec);save();clearScore()}
function clearScore(){['ct1','ct2','home','group','exam'].forEach(x=>$(x).value='')}
function loadScore(){let x=scoreFor($('scoreStudent').value,$('scoreSubject').value);if(!x)return alert('No saved record for this student and subject.');$('ct1').value=x.ct1;$('ct2').value=x.ct2;$('home').value=x.home;$('group').value=x.group;$('exam').value=x.exam}
function delScore(i){if(confirm('Delete this assessment record?')){db.scores.splice(i,1);save()}}
function calc(x){let raw=(Number(x.ct1)||0)+(Number(x.ct2)||0)+(Number(x.home)||0)+(Number(x.group)||0);let cls=raw*.5,ex=(Number(x.exam)||0)*.5,total=cls+ex;return {raw,cls,ex,total,grade:grade(total)}}
function classList(){return [...new Set(db.students.map(s=>s.cls).filter(Boolean))].sort()}
function renderStudents(){let q=($('studentSearch')?.value||'').toLowerCase();let rows=db.students.filter(s=>[s.id,s.name,s.cls,s.section].join(' ').toLowerCase().includes(q));$('studentsBody').innerHTML=rows.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td>${esc(s.cls)}</td><td>${esc(s.section)}</td><td>${esc(s.term)}</td><td>${esc(s.year)}</td><td><button class="btn small secondary" onclick="editStudent('${esc(s.id)}')">Edit</button> <button class="btn small red" onclick="delStudent('${esc(s.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No students found.</td></tr>'}
function renderScores(){let rows=db.scores.map((x,i)=>{let s=studentById(x.studentId),c=calc(x);return `<tr><td>${esc(s?.name||'Unknown')}</td><td>${esc(x.subject)}</td><td>${x.ct1}</td><td>${x.ct2}</td><td>${x.home}</td><td>${x.group}</td><td>${c.cls.toFixed(1)}</td><td>${c.ex.toFixed(1)}</td><td>${c.total.toFixed(1)}</td><td>${c.grade[0]} – ${c.grade[1]}</td><td><button class="btn small red" onclick="delScore(${i})">Delete</button></td></tr>`}).join('');$('scoresBody').innerHTML=rows||'<tr><td colspan="11">No assessment records.</td></tr>'}
function studentResults(cls){let students=db.students.filter(s=>s.cls===cls);return students.map(s=>{let vals=subjects.map(sub=>{let x=scoreFor(s.id,sub);return x?calc(x):null});let totals=vals.map(v=>v?.total||0);let grades=vals.map(v=>v?.grade?.[0]||9);let grand=totals.reduce((a,b)=>a+b,0);let aggregate=grades.slice(0,4).reduce((a,b)=>a+b,0)+grades.slice(4).sort((a,b)=>a-b).slice(0,2).reduce((a,b)=>a+b,0);return {s,vals,totals,grades,grand,aggregate}}).sort((a,b)=>b.grand-a.grand)}
function promotion(grand){return grand>=500?'B9':'REPEATED'}
function aggregateRemark(grand){if(grand>=900)return['Bravo, Keep it Up','Excellent Performance, Keep it Up'];if(grand>=800)return["That's Impressive Performance",'Excellent Performance, Keep it Up'];if(grand>=750)return['Excellent, Keep it Up. Do not Rest On Your Oars. ','Excellent, Keep it Up'];if(grand>=700)return['Very Good, Keep working Hard','Good work done, Keep Improving'];if(grand>=650)return['Good, Can Do Better','More Room For Improvement'];if(grand>=600)return['Good, Can Do Better','Well done but  more room for improvement'];if(grand>=500)return['Average Perfomance','Average Performance, more room for improvement'];if(grand>=450)return['Must Work Hard','You must sit up. There is the need for parental support'];return['Below Average, Must Buck Up','Below average, You must work hard. There is the need for parental support']}
function renderResults(){let cls=$('resultClass').value;if(!cls){$('resultsBody').innerHTML='';return}let arr=studentResults(cls);$('resultsBody').innerHTML=arr.map((r,i)=>{let rm=aggregateRemark(r.grand);return `<tr><td>${ordinal(i+1)}</td><td>${esc(r.s.id)}</td><td>${esc(r.s.name)}</td><td>${esc(r.s.cls)}</td><td>${r.grand.toFixed(1)}</td><td>${r.aggregate}</td><td>${promotion(r.grand)}</td><td>${esc(rm[1])}</td></tr>`}).join('')||'<tr><td colspan="8">No students in this class.</td></tr>'}
function renderReport(){let sid=$('reportStudent').value,s=studentById(sid);if(!s){$('reportCard').innerHTML='<p>No student selected.</p>';return}let arr=studentResults(s.cls),r=arr.find(x=>x.s.id===sid)||studentResults(s.cls)[0],pos=arr.findIndex(x=>x.s.id===sid)+1;let rm=aggregateRemark(r.grand);let rows=subjects.map((sub,i)=>{let x=scoreFor(s.id,sub);let c=x?calc(x):{cls:0,ex:0,total:0,grade:[9,'FAIL']};return `<tr><td>${esc(sub)}</td><td>${c.cls.toFixed(1)}</td><td>${c.ex.toFixed(1)}</td><td>${c.total.toFixed(1)}</td><td>${c.grade[0]}</td><td>${c.grade[1]}</td></tr>`}).join('');$('reportCard').innerHTML=`<div class="report-head"><img src="assets/app-icon.svg"><div class="report-title">PRESEC STAFF 4 BASIC SCHOOL</div><div>P. O. BOX LG 429, LEGON – ACCRA.</div><div><b>END OF TERM EXAMINATION (JHS)</b></div><div><b>STUDENT'S REPORT</b></div></div><div class="report-meta"><div><b>NAME</b><br>${esc(s.name)}</div><div><b>FORM</b><br>${esc(s.cls)}</div><div><b>POSITION</b><br>${ordinal(pos)}</div><div><b>NO. ON ROLL</b><br>${esc(s.roll)}</div><div><b>ID</b><br>${esc(s.id)}</div><div><b>TERM</b><br>${esc(s.term)}</div><div><b>YEAR</b><br>${esc(s.year)}</div><div><b>AGGREGATE</b><br>${r.aggregate}</div></div><table><thead><tr><th>SUBJECT</th><th>CLASS 50%</th><th>EXAM 50%</th><th>TOTAL 100%</th><th>GRADE</th><th>REMARKS</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th>GRAND TOTAL</th><th></th><th></th><th>${r.grand.toFixed(1)}</th><th></th><th>${promotion(r.grand)}</th></tr></tfoot></table><div class="report-notes"><p><b>CONDUCT / ATTITUDE:</b> ${esc($('conduct').value)} &nbsp; <b>INTEREST:</b> ${esc($('interest').value)}</p><p><b>CLASS TEACHER'S REMARKS:</b> ${esc(rm[1])}</p><p><b>HEADTEACHER'S REMARKS:</b> ${esc(rm[0])}</p><p><b>ATTENDANCE:</b> ${esc(s.attendance)} OUT OF ${esc(s.totalAttendance)} &nbsp; <b>DATE VACATED:</b> ${esc($('vacation').value)} &nbsp; <b>RE-OPENING:</b> ${esc($('reopen').value)}</p><p><b>HEADTEACHER'S SIGNATURE:</b> ____________________________</p></div>`}
function refreshSelects(){let opts=db.students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} (${esc(s.cls)})</option>`).join('');['scoreStudent','reportStudent'].forEach(id=>$(id).innerHTML=opts);$('scoreSubject').innerHTML=subjects.map(s=>`<option>${s}</option>`).join('');let classes=classList();$('resultClass').innerHTML=classes.map(c=>`<option>${esc(c)}</option>`).join('');}
function refresh(){if(sessionStorage.unlocked!=='1')return;refreshSelects();renderStudents();renderScores();renderResults();renderReport();$('studentCount').textContent=db.students.length;$('scoreCount').textContent=db.scores.length;$('classCount').textContent=classList().length;let grades=[['1','90–100','Highest'],['2','80–89','Higher'],['3','70–79','High'],['4','60–69','High Average'],['5','55–59','Average'],['6','50–54','Low Average'],['7','40–49','Low'],['8','35–39','Lower'],['9','0–34','Fail']];$('gradeBody').innerHTML=grades.map(g=>`<tr><td>${g[0]}</td><td>${g[1]}</td><td>${g[2]}</td></tr>`).join('')}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='presec-sba-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.students)||!Array.isArray(x.scores))throw 0;db.students.splice(0,db.students.length,...x.students);db.scores.splice(0,db.scores.length,...x.scores);save();alert('Backup restored.')}catch{alert('Invalid backup file.')}};r.readAsText(f)}
function clearAll(){if(confirm('Delete all students and scores from this device?')){db.students.splice(0);db.scores.splice(0);save()}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function closeModal(){$('modal').classList.add('hidden')}
if(sessionStorage.unlocked==='1'){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
refresh();
